
target 'RapydJobs' do
    
  use_frameworks!
  
  pod 'SideMenu'
  pod 'Koloda'
  pod 'Cosmos', '~> 16.0'
  pod 'Segmentio', '~> 3.0'
  pod 'IQKeyboardManagerSwift'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'WARangeSlider'
  pod 'ReactiveSwift', '~> 3.0'
  pod 'ReactiveCocoa', '~> 7.0'
  pod 'Validator'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'SwiftVideoBackground', '~> 3.0'
  pod 'Kingfisher', '~> 4.0'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Socket.IO-Client-Swift'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'QVRWeekView'
  pod 'SkyFloatingLabelTextField'
  pod 'SVProgressHUD'
  pod 'JGProgressHUD'
  pod 'ObjectMapper'
  pod 'DropDown'
  pod 'AFDateHelper', '~> 4.2.2'
  pod 'LinkedinSwift', '~> 1.7.7'
  pod 'GTProgressBar'
  pod 'GrowingTextView'
  pod 'JZCalendarWeekView' #, '0.5.1'
  pod 'SwiftWebVC'
end
